name: Build & deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
     
    - name: check hostname
      run: hostname 
      
    - name: create directory
      run: mkdir ~/Data && cd Data && pwd
      
    - name : create multiple files into Data file
      run: touch file{1..10}.txt  
      
  deploy:
    name: Deploy
    needs: build
    runs-on: self-hosted
    steps:
     
    - name: Download artifact
      uses: actions/checkout@v2
      with:
        name: production-files deploy
        path: mkdir -p /pro-data  && cp -r ~/Data/* /pro-data
        
    
    
    
   
