name: Variables

on:
  push:
    branches: [main]

env:
  PROJECT_ID : PID20211230

jobs:
  java-project:
    runs-on: ubuntu-latest
    steps:
      - name: First script from java ant project
        run: echo We use the global workflow variable in java project $PROJECT_ID
